version: '2.1'
services:
  kafka_exampl:
    build: .
    command: node_modules/.bin/nodemon --harmony --inspect=0.0.0.0:5858 app.js
    depends_on:
      zookeeper:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "3000:3000"
      - "5858:5858"
      - "9229:9229"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app/kafka-exampl
      - /app/kafka-exampl/node_modules

  zookeeper:
    image: zookeeper:3.4
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

    healthcheck:
      # test: ["if [[ $(/bin/zkCli.sh ls /brokers/ids | egrep -o '\[[0-9][0-9, ]*\]' | wc -m)>3 ]]; then exit 0; else exit 1; fi"]
      test: egrep -o \[[0-9][0-9, ]*\] "$(bin/zkCli.sh ls /brokers/ids)"
      test: bin/zkCli.sh -server kafka ls /brokers/ids | egrep -o '\[[0-9][0-9, ]*\]'
      interval: 5s
      timeout: 10s
      retries: 5

  kafka:
    image: ches/kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9021:9021"
      - "7203:7203"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ZOOKEEPER_IP=zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - zookeeper
    # healthcheck:
    #   test: unset JMX_PORT && egrep -o '\[[0-9][0-9, ]*\]' (bin/zookeeper-shell.sh zookeeper:2181 <<< "ls /brokers/ids")
    #   interval: 10s
    #   timeout: 10s
    #   retries: 10
