version: '3'
services:
  
  example_service:
    build: .
    command: npm run dev
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/app
      - /app/node_modules

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: ches/kafka
    hostname: kafka
    depends_on:
      - zookeeper  
    ports:
      - 9092:9092
      - 9021:9021
      - 7203:7203
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ZOOKEEPER_IP=zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock