version: '3'
services:
  
  test_service:
    build: .
    command: npm start
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - .:/app
      - /app/node_modules

  zookeeper:
    image: zookeeper:3.4
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    # restart: unless-stopped

  kafka:
    image: ches/kafka
    hostname: kafka
    depends_on:
      - zookeeper  
    ports:
      - 9092:9092
      - 9021:9021
      - 7203:7203
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ZOOKEEPER_IP=zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
     
    # healthcheck:
    #   test: unset JMX_PORT && egrep -o '\[[0-9][0-9, ]*\]' (bin/zookeeper-shell.sh zookeeper:2181 <<< "ls /brokers/ids")
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    #   # test: /bin/kafka-topics.sh --list --zookeeper zookeeper:2181
    # # restart: unless-stopped
    #   # - ./events:/scripts
    #   #include these to make your kafka instance persistent
    #   # - ./vol/kafka1/data:/data
    #   # - ./vol/kafka1/logs:/logs
    # # entrypoint: ["/start.sh"]
    # #,"/scripts/start-kafka-shell.sh"]
    # # logging:
    # #   driver: none
    # # networks: 
    # #   - stack